name: flutter_question_answer_widget
description: It's a simple and beautiful Question and Answer package for both android & ios.
version: 0.0.1
homepage: https://github.com/vignesh7501/flutter_question_answer_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
